### ISSUE TITLE
Able to select a file after directory is open

### ISSUE THREAD

**Issue by zhouzhuo810** [huynguyennovem/open_dir#10]
Open one dir and select one file in this dir.

**Comment by huynguyennovem** [comment]
It's not supported currently. Can you elaborate on the real use case for this?

**Comment by zhouzhuo810** [comment]
> It's not supported currently. Can you elaborate on the real use case for this?

@huynguyennovem For example, after downloading a file, you need to view the downloaded file, and there are many files in the download directory. You need to find the file you just downloaded. If you can directly select the file, then you do not need to search for it for a long time.

**Comment by huynguyennovem** [comment]
I see. Let's mark this as a feature request

**Comment by huynguyennovem** [comment]
This should be fixed on `open_dir: ^0.0.2`
