### ISSUE TITLE
openNativeDir crash on windows

### ISSUE THREAD

**Issue by GooRingX** [huynguyennovem/open_dir#12]
openNativeDir (path: path, highlightedFileName: highlightedFileName) crashs if highlightedFileName is null(you can not assign null to std::string )

**Comment by huynguyennovem** [comment]
Thanks for the report. Yes, this is a correct bug that happens when passing null to `highlightedFileName`. 

And on macOS, it's fine. But on Linux, an assertion occurs in the console though app runs as desired. 

The fix is on the way.

**Comment by huynguyennovem** [comment]
The fix has been landed:

https://pub.dev/packages/open_dir_windows/changelog#0021
https://pub.dev/packages/open_dir_linux/changelog#0021

please upgrade package: `flutter pub upgrade open_dir`
